var string = "I Work at BITCS"

console.log(string.charAt(0))
console.log(string.charCodeAt(0))
console.log(string.concat(" ", "I am a student"))
console.log(string.endsWith("BITCS"))
console.log(string.includes("Work"))
console.log(string.indexOf("Work"))
console.log(string.lastIndexOf("Work"))
console.log(string.localeCompare("I Work at BITCS"))
console.log(string.match("Work"))
console.log(string.repeat(3))
console.log(string.replace("Work", "Study"))
console.log(string.search("Work"))
console.log(string.slice(0, 3))
console.log(string.split(" "))
console.log(string.startsWith("I"))
console.log(string.substr(0, 3))
console.log(string.substring(0, 3))
console.log(string.toLocaleLowerCase())
console.log(string.toLocaleUpperCase())
console.log(string.toLowerCase())
console.log(string.toString())
console.log(string.toUpperCase())
console.log(string.trim())
console.log(string.valueOf())
